name: my_moobox_app
description: "Plataforma de logística y transporte pesado - Moobox."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  flutter_dotenv: ^5.1.0 

  # --- BACKEND & AUTH ---
  supabase_flutter: ^2.0.2
  
  # --- GESTIÓN DE ESTADO & INYECCIÓN ---
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0

  # --- MAPAS & GPS (COSTO CERO) ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0

  # --- IMÁGENES & UTILIDADES ---
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# ESTA ES LA ÚNICA SECCIÓN "flutter:" QUE DEBE TENER ASSETS
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/