name: my_moobox_app
description: "Plataforma de logística y transporte pesado - Moobox."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  flutter_dotenv: ^5.1.0 

  # --- BACKEND & AUTH ---
  supabase_flutter: ^2.0.2 # Maneja Auth, DB y Storage
  
  # --- GESTIÓN DE ESTADO & INYECCIÓN ---
  flutter_bloc: ^8.1.6     # Para la lógica de pedidos y ofertas
  get_it: ^7.7.0           # Localizador de servicios (Singleton de Supabase)

  # --- MAPAS & GPS (COSTO CERO) ---
  flutter_map: ^6.1.0      # Alternativa gratuita a Google Maps
  latlong2: ^0.9.1         # Manejo de coordenadas para DIRECCIONES
  geolocator: ^11.0.0      # Rastreo en tiempo real del OPERADOR

  # --- IMÁGENES & UTILIDADES ---
  image_picker: ^1.1.2     # Para las fotos de la tabla EVIDENCIA
  flutter_image_compress: ^2.3.0 # Para no saturar el Storage gratuito
  intl: ^0.19.0  
            # Formato de moneda para costos y fechas
  flutter:
    assets:
     - .env # Registra el archivo aquí
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Activa esto cuando tengas tu logo
  # assets:
  #   - assets/images/